# cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: meu-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: meu-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: meu-cluster-role
  apiGroup: rbac.authorization.k8s.io